<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Testcontainers.MsSql" />
    <PackageReference Include="MassTransit" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Services/Ordering/Ordering.Api/Ordering.Api.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="../Shared/*.cs" LinkBase="Shared" />
  </ItemGroup>
</Project>
