<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <UserSecretsId>store-catalog-api</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../Catalog.Infrastructure/Catalog.Infrastructure.csproj" />
    <ProjectReference Include="../../../BuildingBlocks/Store.ServiceDefaults/Store.ServiceDefaults.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Catalog.IntegrationTests" />
  </ItemGroup>
</Project>
